# spring.application.name=auth-service

spring:
  application:
    name: auth-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/mini-project

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  realm: mini-project
  endpoint: http://localhost:8090
  application:
    client-id: auth-service
    client-secret: f76qCsAWdpTtJG2tw4U1jbe8iestlj7l

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info,metrics
#   tracing:
#     sampling:
#       probability: 1.0
#     enabled: true
#   zipkin:
#     tracing:
#       endpoint: http://localhost:9411/api/v2/spans
#       encoding: json

server:
  port: 8100